### ISSUE TITLE
Double-clicking on a contour only selects 3 points

### ISSUE THREAD

**Issue by mrk-z** [googlefonts/fontra#570] opened 2023-06-20 14:04 UTC
Currently double-clicking on a contour only selects 3 points instead of all 4.

This seems to only have appeared recently.

https://github.com/googlefonts/fontra/assets/56224289/6367cecb-f068-4945-8dac-db4334ff9020

**Comment by justvanrossum** [comment] 2023-06-20 14:05
Duplicate of #568 , fixed by #569. I still need to deploy.

**Closed by justvanrossum** 2023-06-20 14:05 UTC
